name: Danger

on: pull_request

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  ENABLE_BARTY_CROUCH: NO

jobs:
  danger:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
        bundler: 2.4.22
        bundler-cache: true

    - name: Cache CocoaPods
      uses: actions/cache@v4
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Pod install
      run: bundle exec pod install

    - name: Run Danger
      run: bundle exec danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
